import {
  BarChart3,
  Bot,
  Box,
  Briefcase,
  Camera,
  Clapperboard,
  Code2,
  Film,
  Gamepad2,
  GraduationCap,
  Landmark,
  Languages,
  Megaphone,
  Mic,
  Music,
  Palette,
  PenLine,
  Podcast,
  Presentation,
  Scale,
  Search,
  Smartphone,
  Sparkles,
  type LucideIcon,
} from 'lucide-react';

/** Иконка категории для карточек и плиток выбора */
export const CATEGORY_ICON: Record<string, LucideIcon> = {
  design: Palette,
  code: Code2,
  writing: PenLine,
  marketing: Megaphone,
  video: Film,
  study: GraduationCap,
  research: Search,
  translation: Languages,
  photo: Camera,
  music: Music,
  '3d': Box,
  animation: Clapperboard,
  presentations: Presentation,
  data: BarChart3,
  mobile: Smartphone,
  gamedev: Gamepad2,
  ai: Bot,
  tutor: GraduationCap,
  legal: Scale,
  finance: Landmark,
  business: Briefcase,
  voiceover: Mic,
  podcast: Podcast,
  other: Sparkles,
};

export const categoryIcon = (c: string): LucideIcon => CATEGORY_ICON[c] ?? Sparkles;
