import {
  Bot,
  Box,
  Briefcase,
  Camera,
  ChartColumn,
  Clapperboard,
  CodeXml,
  Film,
  Gamepad2,
  GraduationCap,
  Landmark,
  Languages,
  Megaphone,
  Mic,
  Music,
  Palette,
  PenLine,
  Presentation,
  Radio,
  Scale,
  Search,
  Smartphone,
  Sparkles,
  type LucideIcon,
} from '@/components/icons';

/** Иконка категории для карточек и плиток выбора */
const MAP: Record<string, LucideIcon> = {
  design: Palette,
  code: CodeXml,
  writing: PenLine,
  marketing: Megaphone,
  video: Film,
  study: GraduationCap,
  research: Search,
  translation: Languages,
  photo: Camera,
  music: Music,
  '3d': Box,
  animation: Clapperboard,
  presentations: Presentation,
  data: ChartColumn,
  mobile: Smartphone,
  gamedev: Gamepad2,
  ai: Bot,
  tutor: GraduationCap,
  legal: Scale,
  finance: Landmark,
  business: Briefcase,
  voiceover: Mic,
  podcast: Radio,
  other: Sparkles,
};

export const categoryIcon = (c: string): LucideIcon => MAP[c] ?? Sparkles;
